### ISSUE TITLE
Please add overlays of remove navbars 

### ISSUE THREAD

**Issue by juvevood** [ohayoubaka/SamsungStatusBar#17]
please! thinks!

**Comment by ohayoubaka** [comment]
You can just hide the navbars yourself, in Settings > Display > Navigation bar > Show and hide button.

**Comment by juvevood** [comment]
I mean that is completely removed -.<

**Comment by ohayoubaka** [comment]
@juvevood wouldn't make much sense, you wouldn't have a way to control your phone's back/home/recents functions then...

**Comment by juvevood** [comment]
@ohayoubaka  I use gestures，so the navigation bar will affect me.

**Comment by ohayoubaka** [comment]
But still, it's not really the point of this theme.

**Comment by juvevood** [comment]
@ohayoubaka  Ok, but really need this point. Thinks your answer.

**Comment by mmihov05** [comment]
GitHub Issues is not the correct way to request features nor is this a feature that will ever be added to an AOSP theme. Let's just stop this discussion here, if you want to talk more use Telegram
