### ISSUE TITLE
Quick settings panel background not right

### ISSUE THREAD

**Issue by seasonyuu** [ohayoubaka/SamsungStatusBar#18]
![photo_2018-01-09_17-49-00](https://user-images.githubusercontent.com/8638535/34714759-6842aa66-f565-11e7-9cde-619abecdd9af.jpg)
Because I'm using dual sim card, so there is a data/phone chooser in quick settings panel, and the background of it isn't translucent

**Comment by ohayoubaka** [comment]
Yeah, some people have told me that. Unfortunately, it's not really possible for me to be able to theme the data/phone chooser panel, since I do not have a dual SIM device myself.

**Comment by seasonyuu** [comment]
if I can fix this by a pull request, would you accept the request?

**Comment by ohayoubaka** [comment]
@seasonyuu Sure, if you can show it to me working.

**Comment by seasonyuu** [comment]
Ok, I will have a try

**Comment by ohayoubaka** [comment]
Can you try the new update and verify if this issue is fixed?

**Comment by MihailMihov** [comment]
He is the one who fixed it and he also tested it. It's working

**Comment by MihailMihov** [comment]
He is the one who fixed it and he also tested it. It's working

**Comment by MihailMihov** [comment]
He is the one who fixed it and he also tested it. It's working

**Comment by MihailMihov** [comment]
He is the one who fixed it and he also tested it. It's working

**Comment by MihailMihov** [comment]
He is the one who fixed it and he also tested it. It's working

**Comment by ohayoubaka** [comment]
Alright, I will assume that this issue is solved, so I'll close it here.
